language: python
python:
  - "2.6"
install:
    - pip install coverage
    - pip install python-coveralls
script:
    - /bin/bash test/unittest_agent1.sh
    - /bin/bash test/unittest_agent2.sh
after_success:
  - coveralls

